# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    # specify the version you desire here
    - image: circleci/node:10.16.3

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

commands:
  install:
    steps:
      - checkout

      # Download cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn

  cache:
    steps:
      # Upload dependencies cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
jobs:
  test:
    <<: *defaults
    steps:
      - install
      - run: yarn typecheck
      - run: yarn check-all
      - run: yarn lint-ts
      - run: yarn lint-css
      - run: yarn test
      - cache

workflows:
  version: 2

  commit:
    jobs:
      - test
